language: node_js
node_js: stable
script: true

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master